### ISSUE TITLE
problem with noise files

### ISSUE THREAD

**Issue by wwyl2000** [AIWintermuteAI/Speech-to-Intent-Micro#3] opened 2023-10-02 17:34 UTC
Hi,

**Question 4: problem with noise files**
I have several noise files. When I tried to train, I found some noise files got error and block the training, while some worked fine. The error i got was:

> Project folder: checkpoints/2023-09-29_19-02-47
> Epoch 1/10
> 2023-09-29 19:02:52.038946: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8101
>  13/722 [..............................] - ETA: 3:45 - loss: 5.6891 - intent_output_loss: 2.2456 - slot_output_loss: 3.4434 - intent_output_accuracy: 0.2139 - slot_output_accuracy: 0.1659 /home/xyz/.local/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
>   out=out, **kwargs)
>  15/722 [..............................] - ETA: 3:50 - loss: 5.4858 - intent_output_loss: 2.1652 - slot_output_loss: 3.3206 - intent_output_accuracy: 0.2250 - slot_output_accuracy: 0.1833 /home/xyz/.local/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in true_divide
>   ret = ret.dtype.type(ret / rcount)
>  16/722 [..............................] - ETA: 5:07 - loss: 5.4210 - intent_output_loss: 2.1519 - slot_output_loss: 3.2691 - intent_output_accuracy: 0.2168 - slot_output_accuracy: 0.1904

I removed some noise files after testing such error, and could finish my training. 
I took a look of the spectrum and wave of the noise files and did not see any problems special. 
Could you please tell me what was the problem?

Thanks,
Willy

**Comment by AIWintermuteAI** [comment] 2023-10-02 19:04
Hello!
From what I see according to the error messages, the problem is not with my code. Therefore closing as out of scope.

**Closed as not planned** 2023-10-02 19:04 UTC
